### ISSUE TITLE
image viewer - feature extraction - legend

### ISSUE THREAD

**Issue by Begalov** [alicevision/meshroom-manual#33]
what does mean three left checkers with corresponding numbers from right?
![image](https://user-images.githubusercontent.com/437009/141313449-68f78258-3002-42ce-ac45-1890fae96693.png)

**Comment by simogasp** [comment]
the three numbers are, in order from left to right, the number of extracted features, the number of matched features, and the number of features that have been reconstructed.
So in your image, you have 117966 sift feature extracted, of which 46098 have a match in other images, and of which 6362 have been reconstructed in 3D

**Comment by Begalov** [comment]
@simogasp  Thanks so much
https://github.com/alicevision/meshroom-manual/compare/develop...Begalov:patch-1
