### ISSUE TITLE
No documentation for ExportAnimatedCamera's Correct Principal Point setting

### ISSUE THREAD

**Issue by Shrinks99** [alicevision/meshroom-manual#34]
After some trial and error today: This option is hugely useful!  Unfortunately there's no information about what it does.

[This tutorial (which was created before this option existed)](https://youtu.be/eiEaHLNJJ94?t=496) showcases the issue that can occur when using Meshroom for matchmove work when this option is ticked on, Meshroom will often incorrectly guess where the centre of the lens should be when exporting the animated camera when compared to the original plate.  In my experience, unchecking this option will result in a lens distortion STMap, camera, and exported undistorted sequence to match the original camera framing accurately.

I assume what this option does is use either Meshroom's guess for where the centre of the lens should be if checked on, or use the centre point coordinates as defined in the CameraInit's Principal Point if unchecked and exports the data accordingly.  If one of the devs can confirm or correct my suspicions I'm happy to contribute this information to the docs & update the tooltip in the program. :)

**Comment by fabiencastan** [comment]
Yes, there is an option to move the optical center to the center of the image. This is useful to use the undistorted plate in some other software like Maya, where there is no notion of optical center.
For using it in Nuke, you don't have to offset the image.
BTW the PrepareDenseScene also undistort the images without moving the optical center (if that's what you need, you may not need to recompute it).
