### ISSUE TITLE
Missing documentation and labeling on CameraInit Distortion Parameters

### ISSUE THREAD

**Issue by Phoenix-64** [alicevision/meshroom-manual#37]
I computed the brown distortion conditions k1 k2 k3 p1 p2 with an OpenCV script and want to use them in Meshroom but i dont know what parameter is corresponding to what.
If the Camera Type in the CameraInit is set to brown and I add 6 distortion parameters they are only labeled 0 trough 5 and not with the brown coefficients labels k1 k2 k3 p1 and p2 do I just have to enter them in this order or did I miss something completely?
Thanks for helping.

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/issues/1647
