### ISSUE TITLE
[How To]

### ISSUE THREAD

**Issue by sumitanilkshirsagar** [alicevision/meshroom-manual#52]
how to enable sequential matching for 3D reconstruction in gui?
If not possible in gui, how to enable in commandline?

**Comment by natowi** [comment]
In the ImageMatching node, you have squential options:

 * **Sequential**
If your input is a video sequence, you can use this option to link images between them over time.
 * **SequentialAndVocabularyTree**
Combines sequential approach with Voc Tree to enable connections between keyframes at different times.

**Comment by sumitanilkshirsagar** [comment]
Hi, Thanks for the reply!
How can I give this from commandline?

**Comment by sumitanilkshirsagar** [comment]
Found the answer:
./meshroom_batch -i image_folder --paramOverrides ImageMatching.method=Sequential --save /path/to/outputfile.mg
